image: quay.io/pypa/manylinux2014_x86_64:latest

before_script:
- /opt/python/cp310-cp310/bin/python --version
- /opt/python/cp310-cp310/bin/python -m venv .venv310
- . .venv310/bin/activate
- pip install .[develop]
- deactivate

test:backend:python3.10:
  stage: test
  script:
  - . .venv310/bin/activate
  - python -m pytest
  - deactivate

pages:
  stage: deploy
  script:
  - . .venv310/bin/activate
  - sphinx-build -b html docs/source public
  - deactivate
  artifacts:
    paths:
    - public

