test:backend:python3.10:
  stage: test
  image: python:3.10-alpine3.15
  script:
    - pip install .[develop]
    - python -m pytest

test:frontend:
  stage: test
  image: zenika/alpine-chrome:with-node
  script:
    - cd mxxn/frontend
    - npm install
    - npm run test -- --single-run

pages:
  stage: deploy
  image: python:3.10-alpine
  script:
    - pip install .[develop]
    - sphinx-build -b html docs/source public
  artifacts:
    paths:
      - public