default:
  image: quay.io/pypa/manylinux2014_x86_64:latest


test:backend:python3.10:
  stage: test
  script:
    - /opt/python/cp310-cp310/bin/python --version
    - /opt/python/cp310-cp310/bin/python -m venv .venv310
    - . .venv310/bin/activate
    - pip install .[develop]
    - python -m pytest
    - deactivate

pages:
  stage: deploy
  script:
    - /opt/python/cp310-cp310/bin/python --version
    - /opt/python/cp310-cp310/bin/python -m venv .venv310
    - . .venv310/bin/activate
    - sphinx-build -b html . public
    - deactivate
  artifacts:
    paths:
    - public
  only:
  - master
