stages:
  - Test

test:python3.10:
  image: quay.io/pypa/manylinux2014_x86_64:latest
  stage: Test
  script:
    - /opt/python/cp310-cp310/bin/python --version
    - /opt/python/cp310-cp310/bin/python -m venv .venv310
    - . .venv310/bin/activate
    - pip install .[develop]
    - python -m pytest
    - deactivate