image: quay.io/pypa/manylinux2014_x86_64:latest

before_script:
  - yum -y install nodejs npm
  - /opt/python/cp310-cp310/bin/python --version
  - /opt/python/cp310-cp310/bin/python -m venv .venv310
  - . .venv310/bin/activate
  - pip install .[develop]
  - deactivate

stages:
  - Test

test_python310:
  stage: Test
  script:
    - . .venv310/bin/activate
    - python -m pytest
    - deactivate
